# Compiler and flags
CXX = g++-14
# -MMD generates .d files, -MP prevents errors if a header is deleted
CXXFLAGS = -std=c++23 -Wall -Wextra -Wpedantic -I$(INCLUDE_DIR) -O2 -MMD -MP

# Directories
SRC_DIR = src
OBJ_DIR = obj
BIN_DIR = bin
INCLUDE_DIR = includes

# Files
SOURCES = $(shell find $(SRC_DIR) -name '*.cpp')
OBJECTS = $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SOURCES))
# These correspond to the .d files generated by -MMD
DEPS = $(OBJECTS:.o=.d)
TARGET = $(BIN_DIR)/argent

# Default rule
all: directories $(TARGET)

# Link all object files
$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@

# Compile each source file and generate dependency info
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Include the dependency files (the "-" ignores errors if they don't exist yet)
-include $(DEPS)

# Create necessary directories
directories:
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)

# Clean up
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)

.PHONY: all clean directories